version: '3.7'

services:

  web:
    build: ./api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src/api
    ports:
      - 8000:8000
    networks:
      - main
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web
    depends_on:
      - web-db

  web-db:
    image: postgres:12-alpine
    expose:
      - 5432
    networks:
      - main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web

networks:
  main:
    driver: bridge